// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCn4b7UppnWnCmeABqrOhACqkOKCh_0L64',
    appId: '1:1046723306402:web:b92f9b91603ac6a803c8fb',
    messagingSenderId: '1046723306402',
    projectId: 'esnafsepetim',
    authDomain: 'esnafsepetim.firebaseapp.com',
    storageBucket: 'esnafsepetim.firebasestorage.app',
    measurementId: 'G-HF4N5R521T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpYPAF4ubDVG9_WbCcEsNIMTjfh3oXEpA',
    appId: '1:1046723306402:android:5f0eb21bb88b2c4d03c8fb',
    messagingSenderId: '1046723306402',
    projectId: 'esnafsepetim',
    storageBucket: 'esnafsepetim.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxRssKRj_rNRDFwsKbVPe-UCJkfwuQxjI',
    appId: '1:1046723306402:ios:e9680852c67c288503c8fb',
    messagingSenderId: '1046723306402',
    projectId: 'esnafsepetim',
    storageBucket: 'esnafsepetim.firebasestorage.app',
    iosBundleId: 'com.example.esnafPos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxRssKRj_rNRDFwsKbVPe-UCJkfwuQxjI',
    appId: '1:1046723306402:ios:e9680852c67c288503c8fb',
    messagingSenderId: '1046723306402',
    projectId: 'esnafsepetim',
    storageBucket: 'esnafsepetim.firebasestorage.app',
    iosBundleId: 'com.example.esnafPos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCn4b7UppnWnCmeABqrOhACqkOKCh_0L64',
    appId: '1:1046723306402:web:3e4ed694f3125a0203c8fb',
    messagingSenderId: '1046723306402',
    projectId: 'esnafsepetim',
    authDomain: 'esnafsepetim.firebaseapp.com',
    storageBucket: 'esnafsepetim.firebasestorage.app',
    measurementId: 'G-6VDRTZGS43',
  );
}
